In [ ]:
pip install --upgrade pip

In [ ]:
pip install numpy

### Single dimensional array


In [8]:
import numpy as np

# create array
arr = np.array([1, 2, 3, 4, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 4 5]
<class 'numpy.ndarray'>


### Tow dimensional array


In [ ]:
import numpy as np

tow_d_arr = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
print(tow_d_arr)
print(type(tow_d_arr))

[[1 2 3 4]
 [1 2 3 4]]
<class 'numpy.ndarray'>


### Creating 3D array


In [13]:
import numpy as np

three_d_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print(three_d_array)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


### dtype parameter --> wich can help us out with deciding about the size of the data we are going to store inside our array


In [16]:
import numpy as np

np.array([1, 2, 3, 4], dtype=np.int32)

array([1, 2, 3, 4], dtype=int32)

In [17]:
import numpy as np

np.array([1, 2, 3, 4, 5, 6, 7, 8], dtype=np.int64)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
## np.float64, np.float32

In [18]:
import numpy as np

np.array([1, 0, -1, 3, 2, -3], dtype=bool)

array([ True, False,  True,  True,  True,  True])

### arrange function
It helps us out with providing the values over a certaion range

In [19]:
empty_list = []

for i in range(16):
    empty_list.append(i)

print(empty_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [20]:
import numpy as np

np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])